export default {
  FETCH_BOOK_LISTS_REQUEST: "FETCH_BOOK_LISTS_REQUEST",
  FETCH_BOOK_LISTS_SUCCESS: "FETCH_BOOK_LISTS_SUCCESS",
  FETCH_BOOK_LISTS_FAILURE: "FETCH_BOOK_LISTS_FAILURE",

  FETCH_BOOK_REQUEST: "FETCH_BOOK_REQUEST",
  FETCH_BOOK_SUCCESS: "FETCH_BOOK_SUCCESS",
  FETCH_BOOK_FAILURE: "FETCH_BOOK_FAILURE",

  CREATE_BOOK_REQUEST: "CREATE_BOOK_REQUEST",
  CREATE_BOOK_SUCCESS: "CREATE_BOOK_SUCCESS",
  CREATE_BOOK_FAILURE: "CREATE_BOOK_FAILURE",

  EDIT_BOOK_REQUEST: "EDIT_BOOK_REQUEST",
  EDIT_BOOK_SUCCESS: "EDIT_BOOK_SUCCESS",
  EDIT_BOOK_FAILURE: "EDIT_BOOK_FAILURE",

  DELETE_BOOK_REQUEST: "DELETE_BOOK_REQUEST",
  DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",
  DELETE_BOOK_FAILURE: "DELETE_BOOK_FAILURE",

  CLOSE_RESULT_MODAL: "CLOSE_RESULT_MODAL"
};
